name: OData export (weekly + manual)

on:
  schedule:
    # Sunday 07:00 UTC == 12:00 UTC+5 (Asia/Almaty)
    - cron: '0 7 * * 0'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run exporter
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
          PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
        run: |
          python main.py

      - name: Commit & push CSVs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: weekly raw OData export"
          file_pattern: output/*.csv
          branch: main
