name: OData → CSV export

on:
  schedule:
    # Every Sunday 07:00 UTC == 12:00 Asia/Almaty (UTC+5)
    - cron: '0 7 * * 0'
  workflow_dispatch: {}  # manual run button

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run exporter
        env:
          ODATA_URL: ${{ secrets.ODATA_URL }}
          ODATA_USER: ${{ secrets.ODATA_USER }}
          ODATA_PASS: ${{ secrets.ODATA_PASS }}
        run: |
          python main.py

      - name: Commit & push CSVs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): weekly OData export (overwrite)"
          file_pattern: data/*.csv
          branch: main
